export const queryKeys = {
  authUser: ['auth', 'user'] as const,
  homeFeed: ['posts', 'home'] as const,
  churchFeed: (churchId?: string) => ['posts', 'church', churchId] as const,
  globalFeed: ['posts', 'global'] as const,
  communityFeed: (communityId: string) => ['posts', 'community', communityId] as const,
  forYouFeed: ['posts', 'for-you'] as const,
  postLiked: (postId: string) => ['posts', 'liked', postId] as const,
  comments: (postId: string) => ['comments', postId] as const,
  churches: ['churches'] as const,
  myCommunities: ['communities', 'mine'] as const,
  communityMembers: (communityId: string) => ['communities', 'members', communityId] as const,
  communityJoinRequests: (communityId: string) => ['communities', 'join-requests', communityId] as const,
  myJoinRequestStatus: (communityId: string) => ['communities', 'my-join-status', communityId] as const,
  communityGoals: (communityId: string) => ['communities', 'goals', communityId] as const,
  publicCommunities: ['communities', 'public'] as const,
  communityRequests: ['communities', 'requests'] as const,
  goals: ['goals'] as const,
  goalProgress: (goalId: string) => ['goals', 'progress', goalId] as const,
  savedVerses: ['saved-verses'] as const,
  communityMessages: (communityId: string) => ['community', 'messages', communityId] as const,
  directChats: ['direct', 'chats'] as const,
  directMessages: (chatId: string) => ['direct', 'messages', chatId] as const,
  userStreak: ['users', 'streak'] as const,
  bibleBooks: ['bible', 'books'] as const,
  bibleChapters: (bookId: string) => ['bible', 'chapters', bookId] as const,
  bibleVerses: (chapterId: string) => ['bible', 'verses', chapterId] as const,
  bibleSearch: (query: string) => ['bible', 'search', query] as const,
  bibleReference: (reference: string) => ['bible', 'reference', reference] as const,
  readingProgress: (userId: string) => ['reading-progress', userId] as const,
};
